### ISSUE TITLE
Buttons in terminal are not responsive

### ISSUE THREAD

**Issue by Arav1nd2** [dsc-sastra-university/dsc-web-page#6]
The red, green and yellow buttons in terminal look fine in mobile devices but look very large in desktops in different resolutions

**Comment by Ram-the-coder** [comment]
They look fine.... Is it still there? If yes, can u share a screenshot?

**Comment by Arav1nd2** [comment]
The top menubar is expanding with changing screen sizes. I am working on same terminal using flexbox instead of grid
